#!/usr/bin/env python3
"""
Generate errors/registry.json from all category YAML files.
Run this after adding or updating any error entry.

Usage: python errors/generate_registry.py

v0.5 (Op-47): Build fails on duplicate codes, missing codes, or malformed entries.
Exits with non-zero status for CI integration.
"""

import json
import yaml
import sys
from pathlib import Path

CATEGORY_FILES = [
    "transport.yaml",
    "catalog.yaml",
    "transaction.yaml",
    "fulfillment.yaml",
    "post-order.yaml",
    "settlement.yaml",
    "network.yaml",
    "schema.yaml",
    "system.yaml",
]

REQUIRED_FIELDS = ["code", "http_status", "category", "title", "description", "resolution"]


def generate():
    errors_dir = Path(__file__).parent
    all_errors = []
    seen_codes = {}
    fatal_errors = []

    for filename in CATEGORY_FILES:
        filepath = errors_dir / filename
        if not filepath.exists():
            fatal_errors.append(f"{filename}: file missing (listed in CATEGORY_FILES)")
            continue

        with open(filepath) as f:
            try:
                entries = yaml.safe_load(f) or []
            except yaml.YAMLError as e:
                fatal_errors.append(f"{filename}: YAML parse error — {e}")
                continue

        if not isinstance(entries, list):
            fatal_errors.append(f"{filename}: top-level must be a list of error objects")
            continue

        for i, entry in enumerate(entries):
            if not isinstance(entry, dict):
                fatal_errors.append(f"{filename}[{i}]: entry is not an object")
                continue

            code = entry.get("code")
            if not code:
                fatal_errors.append(f"{filename}[{i}]: missing 'code' field")
                continue

            # Check required fields
            missing = [k for k in REQUIRED_FIELDS if k not in entry]
            if missing:
                fatal_errors.append(f"{code} in {filename}: missing required fields — {missing}")
                continue

            # Validate code format: ION-Nxxx
            if not (code.startswith("ION-") and len(code) == 8 and code[4:].isdigit()):
                fatal_errors.append(f"{code} in {filename}: malformed code (expected ION-Nxxx)")
                continue

            # Check for duplicates (HARD FAIL in v0.5)
            if code in seen_codes:
                fatal_errors.append(
                    f"DUPLICATE: {code} in {filename} — first seen in {seen_codes[code]}"
                )
                continue
            seen_codes[code] = filename

            # Title and description must have at minimum 'en' key
            if not isinstance(entry.get("title"), dict) or "en" not in entry["title"]:
                fatal_errors.append(f"{code} in {filename}: title must be bilingual with at least 'en' key")
                continue
            if not isinstance(entry.get("description"), dict) or "en" not in entry["description"]:
                fatal_errors.append(f"{code} in {filename}: description must be bilingual with at least 'en' key")
                continue
            if not isinstance(entry.get("resolution"), dict) or "en" not in entry["resolution"]:
                fatal_errors.append(f"{code} in {filename}: resolution must have at least 'en' key")
                continue

            all_errors.append(entry)

    if fatal_errors:
        print("ERROR: Error registry validation failed:", file=sys.stderr)
        for err in fatal_errors:
            print(f"  - {err}", file=sys.stderr)
        print(f"\n{len(fatal_errors)} error(s) — registry NOT regenerated", file=sys.stderr)
        sys.exit(1)

    # Sort by code
    all_errors.sort(key=lambda e: e.get("code", ""))

    registry = {
        "_generated": "Do not edit this file directly. Run generate_registry.py instead.",
        "_source": "errors/*.yaml",
        "_validationPolicy": "v0.5 (Op-47): Build fails on duplicate codes, missing codes, or malformed entries.",
        "count": len(all_errors),
        "errors": all_errors
    }

    output_path = errors_dir / "registry.json"
    with open(output_path, "w") as f:
        json.dump(registry, f, indent=2, ensure_ascii=False)

    print(f"Generated registry.json with {len(all_errors)} errors")
    print(f"Codes: {min(seen_codes.keys())} .. {max(seen_codes.keys())}")


if __name__ == "__main__":
    generate()
