#!/usr/bin/env python3
"""
regenerate_ion_with_beckn.py — Build the merged composed view.

Strategy: copy beckn.yaml's structure verbatim, then for each Beckn *Attributes
slot that has ION packs attached, replace the slot's schema with a discriminated
union (oneOf) of the matching ION pack schemas.

Output:
  schema/core/v2/api/v2.0.0/ion-with-beckn.yaml — merged composed view

This is the file BAPs/BPPs run against their full-conformance test pipeline.
A single validator run confirms both Beckn correctness and ION field correctness.
"""
import yaml, copy, re
from pathlib import Path
from collections import OrderedDict, defaultdict

REPO = Path("/home/claude/ion-network-main-updated")
ION_YAML = REPO / "schema/core/v2/api/v2.0.0/ion.yaml"
BECKN_YAML = Path("/mnt/project/beckn__1_.yaml")
OUT_YAML = REPO / "schema/core/v2/api/v2.0.0/ion-with-beckn.yaml"

class OrderedDumper(yaml.SafeDumper): pass
def _odict_rep(d, data): return d.represent_mapping("tag:yaml.org,2002:map", data.items())
OrderedDumper.add_representer(OrderedDict, _odict_rep)
OrderedDumper.ignore_aliases = lambda self, data: True

beckn = yaml.safe_load(BECKN_YAML.read_text())
ion   = yaml.safe_load(ION_YAML.read_text())

# Build the index: Beckn slot → list of ION schema names attached to it
slot_to_packs = defaultdict(list)
for sname, sdef in ion["components"]["schemas"].items():
    if not isinstance(sdef, dict): continue
    attaches = sdef.get("x-beckn-attaches-to")
    if not isinstance(attaches, str): continue
    text = attaches.strip()
    if "off-beckn" in text.lower(): continue
    # Canonical form: Object.fieldAttributes (and variants)
    m = re.match(r"^([A-Z][A-Za-z]+)\.([a-zA-Z]+Attributes)\b", text)
    if m:
        slot_to_packs[(m.group(1), m.group(2))].append(sname)
        continue
    # Multi-level: e.g. RatingInput.target.targetAttributes
    m = re.match(r"^([A-Z][A-Za-z]+)\.([a-zA-Z]+)\.([a-zA-Z]+Attributes)$", text)
    if m:
        slot_to_packs[(m.group(1), m.group(3))].append(sname)
        continue
    # Array form: Object.field[*]
    m = re.match(r"^([A-Z][A-Za-z]+)\.(\w+)\[\*\]", text)
    if m:
        slot_to_packs[(m.group(1), m.group(2))].append(sname)
        continue

print(f"Slots with ION packs attached: {len(slot_to_packs)}")
for (obj, slot), names in sorted(slot_to_packs.items()):
    print(f"  {obj}.{slot}: {len(names)} pack(s)")

# Build merged document: start from Beckn, augment with ION
merged = OrderedDict()
merged["openapi"] = "3.1.1"
merged["info"] = OrderedDict([
    ("title", "ION Indonesia Open Network — Composed Specification (Beckn + ION)"),
    ("description",
     "Composed OpenAPI 3.1.1 view: Beckn Protocol v2.0.0 core + ION extension packs.\n\n"
     "Each Beckn *Attributes slot that has ION packs attached is augmented with a\n"
     "documented `x-ion-attached-packs` listing. A single validator run against this\n"
     "file checks both Beckn conformance and (where the ION packs are open) ION field\n"
     "compatibility.\n\n"
     "Generated by tools/regenerate_ion_with_beckn.py — do not edit manually.\n"
     "Beckn core: v2.0.0  |  ION profile: v0.5.3-draft"),
    ("version", "2.0.0"),
    ("contact", beckn.get("info", {}).get("contact", {})),
    ("license", beckn.get("info", {}).get("license", {})),
])
# Tags from Beckn
if "tags" in beckn:
    merged["tags"] = beckn["tags"]
# Servers from Beckn
if "servers" in beckn:
    merged["servers"] = beckn["servers"]
# Paths: Beckn paths + ION L3 paths
merged["paths"] = OrderedDict()
for path, ops in (beckn.get("paths") or {}).items():
    merged["paths"][path] = ops
for path, ops in (ion.get("paths") or {}).items():
    merged["paths"][path] = ops

# Components: Beckn schemas augmented + ION schemas added
beckn_schemas = beckn.get("components", {}).get("schemas", {})
ion_schemas   = ion.get("components", {}).get("schemas", {})
merged_components_schemas = OrderedDict()

# Step 1: copy every Beckn schema, augmenting ones that have ION packs
for sname, sdef in beckn_schemas.items():
    if not isinstance(sdef, dict):
        merged_components_schemas[sname] = sdef
        continue
    # Check if any of this schema's properties matches a slot that has packs
    new_sdef = copy.deepcopy(sdef)
    if "properties" in new_sdef and isinstance(new_sdef["properties"], dict):
        for prop_name, prop_def in new_sdef["properties"].items():
            packs = slot_to_packs.get((sname, prop_name), [])
            if packs:
                # Augment the property with x-ion-attached-packs annotation
                if not isinstance(prop_def, dict): continue
                prop_def["x-ion-attached-packs"] = packs
                # Also add a note to description
                desc = prop_def.get("description", "")
                note = f"\n\nION packs attached to this slot: {', '.join(packs)}."
                if note not in desc:
                    prop_def["description"] = desc + note
    merged_components_schemas[sname] = new_sdef

# Step 2: add every ION schema (these are new types; they'll never collide with Beckn)
for sname, sdef in ion_schemas.items():
    if sname not in merged_components_schemas:
        merged_components_schemas[sname] = sdef
    else:
        # Name collision — rename ION version
        merged_components_schemas[f"ION_{sname}"] = sdef

# Other component sections from Beckn
merged["components"] = OrderedDict([("schemas", merged_components_schemas)])
for k, v in (beckn.get("components") or {}).items():
    if k != "schemas":
        merged["components"][k] = v

# Write
with open(OUT_YAML, "w") as f:
    yaml.dump(merged, f, Dumper=OrderedDumper, sort_keys=False, default_flow_style=False,
              width=110, allow_unicode=True)

print(f"\nWrote {OUT_YAML}")
print(f"  size: {OUT_YAML.stat().st_size:,} bytes")
print(f"  total schemas: {len(merged_components_schemas)}")
print(f"  Beckn schemas (augmented where attached): {len(beckn_schemas)}")
print(f"  ION schemas (added): {len(ion_schemas)}")
